In [76]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

In [77]:
iris=pd.read_excel('credit_score.xlsx')

In [78]:
iris.head()

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,kpr_aktif,durasi_pinjaman_bulan,jumlah_tanggungan,rata_rata_overdue,risk_rating
0,1,AGR-000001,295,YA,48,5,61 - 90 days,4
1,2,AGR-000011,271,YA,36,5,61 - 90 days,4
2,3,AGR-000030,159,TIDAK,12,0,0 - 30 days,1
3,4,AGR-000043,210,YA,12,3,46 - 60 days,3
4,5,AGR-000049,165,TIDAK,36,0,31 - 45 days,2

In [79]:
iris['risk_rating'].unique()

array([4, 1, 3, 2, 5])

In [80]:
iris.describe(include='all')

,Unnamed: 0,kode_kontrak,pendapatan_setahun_juta,kpr_aktif,durasi_pinjaman_bulan,jumlah_tanggungan,rata_rata_overdue,risk_rating
count,900.000000,900,900.000000,900,900.000000,900.000000,900,900.000000
unique,NaN,900,NaN,2,NaN,NaN,5,NaN
top,NaN,AGR-000001,NaN,YA,NaN,NaN,46 - 60 days,NaN
freq,NaN,1,NaN,513,NaN,NaN,291,NaN
mean,450.500000,NaN,163.318889,NaN,29.933333,2.932222,NaN,2.681111
std,259.951919,NaN,51.863210,NaN,13.671988,2.007457,NaN,1.294928
min,1.000000,NaN,70.000000,NaN,12.000000,0.000000,NaN,1.000000
25%,225.750000,NaN,121.000000,NaN,12.000000,1.000000,NaN,1.000000
50%,450.500000,NaN,162.000000,NaN,24.000000,3.000000,NaN,3.000000
75%,675.250000,NaN,199.000000,NaN,48.000000,5.000000,NaN,3.000000
max,900.000000,NaN,300.000000,NaN,48.000000,6.000000,NaN,5.000000

In [81]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900 entries, 0 to 899
Data columns (total 8 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               900 non-null    int64
 1   kode_kontrak             900 non-null    object
 2   pendapatan_setahun_juta  900 non-null    int64
 3   kpr_aktif                900 non-null    object
 4   durasi_pinjaman_bulan    900 non-null    int64
 5   jumlah_tanggungan        900 non-null    int64
 6   rata_rata_overdue        900 non-null    object
 7   risk_rating              900 non-null    int64
dtypes: int64(5), object(3)
memory usage: 56.4+ KB

In [82]:
iris.drop(columns="kode_kontrak",inplace=True)

In [67]:
iris.isnull().sum()

Unnamed: 0                 0
pendapatan_setahun_juta    0
kpr_aktif                  0
durasi_pinjaman_bulan      0
jumlah_tanggungan          0
rata_rata_overdue          0
risk_rating                0
dtype: int64

In [68]:
iris.corr()

,Unnamed: 0,pendapatan_setahun_juta,durasi_pinjaman_bulan,jumlah_tanggungan,risk_rating
Unnamed: 0,1.000000,0.098583,0.024219,0.075706,0.127253
pendapatan_setahun_juta,0.098583,1.000000,-0.052143,0.250064,0.144934
durasi_pinjaman_bulan,0.024219,-0.052143,1.000000,0.028773,0.237424
jumlah_tanggungan,0.075706,0.250064,0.028773,1.000000,0.762335
risk_rating,0.127253,0.144934,0.237424,0.762335,1.000000

In [69]:
X=iris.iloc[:,0:4].values
y=iris.iloc[:,4].values

In [73]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [70]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score ,precision_score,recall_score,f1_score
from sklearn.model_selection import KFold,train_test_split,cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.linear_model import  LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import linear_model
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC, LinearSVC
from sklearn.naive_bayes import GaussianNB

In [71]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=0)

In [74]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)
Y_pred = gaussian.predict(X_test) 
accuracy_nb=round(accuracy_score(y_test,Y_pred)* 100, 2)
acc_gaussian = round(gaussian.score(X_train, y_train) * 100, 2)

cm = confusion_matrix(y_test, Y_pred)
accuracy = accuracy_score(y_test,Y_pred)
precision =precision_score(y_test, Y_pred,average='micro')
recall =  recall_score(y_test, Y_pred,average='micro')
f1 = f1_score(y_test,Y_pred,average='micro')
print('Confusion matrix for Naive Bayes\n',cm)
print('accuracy_Naive Bayes: %.3f' %accuracy)
print('precision_Naive Bayes: %.3f' %precision)
print('recall_Naive Bayes: %.3f' %recall)
print('f1-score_Naive Bayes : %.3f' %f1)

ValueError: ignored